name: pub_package_monorepo
repository: https://github.com/GenieCoderSrc/pub_package_monorepo

packages:
  - "packages/*"

ignore:
  - "packages/**/build/**"
  - "packages/**/.dart_tool/**"

# -----------------------------
# Commands and Versioning
# -----------------------------
command:
  version:
    linkToCommits: false        # <-- Change this to false for manual version control
    updateGitTagRefs: false     # <-- Since you are handling versions manually
    workspaceChangelog: false

  bootstrap:
    runPubGetInParallel: true

# -----------------------------
# Useful Scripts
# -----------------------------
scripts:
  analyze:
    run: flutter analyze

  format:
    run: dart format .

  test:
    run: flutter test --coverage