name: pub_package_monorepo
description: Genie Coder Dart/Flutter package monorepo
version: 0.0.1
publish_to: "none"

environment:
  sdk: '>=3.11.0 <4.0.0' # Updated to support glob workspace syntax

workspace:
  - packages/*

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  melos: ^8.9.0

melos:
  repository: https://github.com/GenieCoderSrc/pub_package_monorepo

  ignore:
    - "packages/**/build/**"
    - "packages/**/.dart_tool/**"

  command:
    version:
      linkToCommits: false
      updateGitTagRefs: false
      workspaceChangelog: false

    bootstrap:
      runPubGetInParallel: true

  scripts:
    analyze:
      run: flutter analyze

    format:
      run: dart format .

    test:
      run: flutter test --coverage